kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tkb
networking:
  ipFamily: dual        
nodes:
- role: control-plane
  image: kindest/node:v1.26.0
- role: worker
  image: kindest/node:v1.26.0
- role: worker
  image: kindest/node:v1.26.0
- role: worker
  image: kindest/node:v1.26.0
